### ISSUE TITLE
PullImage only pulls if the image doesn't exist locally

### ISSUE THREAD

**Issue by WheresAlice** [skybet/cali#37] opened 2018-03-30 15:00 UTC
The code to pull Docker images always exits if the image exists.  There should be an option to still pull the image in order to get the latest version.  I think this just needs an extra parameter to PullImage and the if statement changing on line 361:

https://github.com/skybet/cali/blob/master/docker.go#L361

**Comment by lucymhdavies** [comment] 2018-03-30 15:01
Duplicate of https://github.com/skybet/cali/issues/3

**Closed** 2018-03-30 15:01 UTC
Labels: duplicate
